background = #171717
foreground = #CCD0CF
cursor-color = #aeab94
selection-background = #CCD0CF
selection-foreground = #171717

palette = 0=#171717
palette = 1=#aeab94
palette = 2=#F25623
palette = 3=#4D4D4D
palette = 4=#88A57D
palette = 5=#F56E0F
palette = 6=#8A8A8A
palette = 7=#bcbfbc
palette = 8=#333333
palette = 9=#aeab94
palette = 10=#F25623
palette = 11=#4D4D4D
palette = 12=#88A57D
palette = 13=#F56E0F
palette = 14=#8A8A8A
palette = 15=#757d75
