# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgb(706e5e)
    col.inactive_border = rgb(171717)
    border_size = 3
    gaps_in = 5
    gaps_out = 5
}

decoration {
  rounding = 4
  rounding_power = 3
  shadow {
  enabled = yes
  render_power = 8
  range = 8
  color = rgba(22,22,22, 0.5)
  }
}